apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: invoiceninja
  namespace: invoiceninja
spec:
  interval: 1h
  chart:
    spec:
      chart: invoiceninja
      version: "5.10.26"
      sourceRef:
        kind: HelmRepository
        name: invoiceninja
        namespace: flux-system
  install:
    createNamespace: true
  values:
    ingress:
      hostname: billing.asdfx.us
      tls: true
      certManager: false
    existingSecret: invoiceninja-passwords
    mariadb:
      auth:
        existingSecret: invoiceninja-passwords
    redis:
      auth:
        existingSecret: invoiceninja-passwords
        existingSecretPasswordKey: redis-password