apiVersion: "secretgenerator.mittwald.de/v1alpha1"
kind: "StringSecret"
metadata:
  name: "invoiceninja-passwords"
  namespace: "invoiceninja"
spec:
  forceRegenerate: false
  data: {}
  fields:
    - fieldName: "APP_KEY"
      encoding: "base64"
      length: "32"
    - fieldName: "mariadb-root-password"
      encoding: "base64"
      length: "15"
    - fieldName: "mariadb-replication-password"
      encoding: "base64"
      length: "15"
    - fieldName: "mariadb-password"
      encoding: "base64"
      length: "15"
    - fieldName: "redis-password"
      encoding: "base64"
      length: "15"
