apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: core
  namespace: flux-system
spec:
  interval: 1h
  path: clusters/home/core
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
