apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: infrastructure
  namespace: flux-system
spec:
  dependsOn:
    - name: core
  interval: 1h
  path: ./clusters/home/infrastructure
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system