apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kubernetes-secret-generator
  namespace: flux-system
spec:
  interval: 1h
  chart:
    spec:
      chart: kubernetes-secret-generator
      version: "3.4.1"
      sourceRef:
        kind: HelmRepository
        name: mittwald
        namespace: flux-system
  install:
    createNamespace: true
