apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cloudflared
  namespace: cloudflared
spec:
  interval: 1h
  chart:
    spec:
      chart: cloudflare-tunnel
      version: "0.3.2"
      sourceRef:
        kind: HelmRepository
        name: cloudflare
        namespace: flux-system
  install:
    createNamespace: true
  values:
    cloudflare:
      tunnelName: 'k3s-homelab'
      secretName: cloudflared-credentials