---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflared-credentials
  namespace: cloudflared
spec:
  encryptedData:
    credentials.json: AgCfTx2jqQuyJ9eCaQ9lzgB5y7/RcoBwn7lhEG5NdEt/HxSz1s/Th9e0fEW3WK6ttTvGv2Ax9m2EMfnxFDFK5QN2+Y1irvY3DCv2AmgUtExOEqKsoyAw10v5a2LcZed2c0bKwM1ASvhOR/jFEnVzl0aHsnbdfW4EpcA0riTsx4fBK343FMH/749DMhh1zvJXlDaNFmr4YgPKJ0qQevoRxFkJ5VFdnIgJHxEKZhzGwL5NEkpC2vMXzgGsvVP5HoinvLo2lEya9jFUs5R+o/m6mBSX1ZUNV/ZQBeAW1A/ewcrUF+sxoOsGgrtRVojdKoW0CiPOQA9SpSUBJ75YZgCFxmqp462yM6eaDlVVLFuj1ra8hPYPW/E0bvGw7bJv8JFTnGKlr6LdLbLnqUcpHHOhtykv1cdtAURt9BAi9ExaFbr4r8vp81XyyMjfgROigwmQfsI8jIo5fMbB+MDX2n3MMtzlQTA2+yduG2XDjzRlbtn2Ssn4ZHnZaUn1LWyy5Be58GTMV1Vhcgb4z9dVbVThAFY9B7yzzTqpX4xqHit0LRSQkCkQlYzw1pgs07gihgGg6SUrpiyu1C5nYUDkHtwNSujVdhQ6u4h5n2NnjcB23cbZkR8fdi6enxBMVayukYLnjs7CQzMo+mRci93V5CPljG2nctJEuJ9GD9M4uCkLVVe2ymahDaR0HwmHIB1PhVgaopB3BAxJC90gWkC+akO8ldyxeunaDKvm/9cCF+NEf9prrZJ1mOJnhtxIo2+G48HqiqNECzBPwBHj3IhZxwaSXJSA5RxbLBdy3DDCuTehRatJ7Mk9EAbonX7AW7XOrcZz5ONhcjcjs4VXqeFN1OsaeV91CGR/APbIlmgOGNDXI0cuKYb2XSmGO1W3KnH6RF2KPjTzb8LdVia+vbylEV6fE450Vw==
  template:
    metadata:
      creationTimestamp: null
      name: cloudflared-credentials
      namespace: cloudflared
